#![allow(dead_code)]

xflags::xflags! {
    src "./src/flags.rs"

    /// Utility tasks for Eden's backend repository.
    cmd xtask {
        /// Docker-related utility tasks for the Eden project
        ///
        /// If you wish to run any of these commands, you're required to install
        /// Docker in your system or development environment.
        cmd docker {
            /// Builds Eden docker image with `Dockerfile` located at the root
            /// directory of the Eden project repository.
            cmd build {
                /// Rust build profile to use when building the Eden docker image.
                /// (default: release)
                optional --profile profile: String

                /// Set custom image repository to create Eden docker image reference.
                /// (default: memothelemo/eden)
                optional -r, --repository repository: String

                /// Set custom version to append to the image repository. (e.g. memothelemo/eden:1.0.0)
                /// (default: {CARGO_PKG_VERSION})
                optional --version version: String
            }
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Docker(Docker),
}

#[derive(Debug)]
pub struct Docker {
    pub subcommand: DockerCmd,
}

#[derive(Debug)]
pub enum DockerCmd {
    Build(Build),
}

#[derive(Debug)]
pub struct Build {
    pub profile: Option<String>,
    pub repository: Option<String>,
    pub version: Option<String>,
}

impl Xtask {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
